package entities;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBDocument
@DynamoDBTable(tableName = "NguoiDung")
public class NguoiDung {

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	private String id;

	@DynamoDBAttribute
	private String email;
	
	@DynamoDBAttribute
	private String password;
	
	@DynamoDBAttribute
    private String username;

	@DynamoDBAttribute
	private String status;
	
	@DynamoDBAttribute
	private String ngayTao;
	
	@DynamoDBAttribute(attributeName = "friendID")
	private List<String> friends;
	
	public NguoiDung() {
	}

	public NguoiDung(String email, String password, String username) {
		this.email = email;
		this.password = password;
		this.username = username;
		this.status = "offline";
		this.ngayTao = DateTimeFormatter.ofPattern("dd/MM/yyyy").format(LocalDate.now());
	}

	public NguoiDung(String email, String password) {
		super();
		this.email = email;
		this.password = password;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getNgayTao() {
		return ngayTao;
	}

	public void setNgayTao(String ngayTao) {
		this.ngayTao = ngayTao;
	}

	public List<String> getFriends() {
		return friends;
	}
	
	public void setFriends(List<String> friends) {
		this.friends = friends;
	}
	
	@Override
	public String toString() {
		return "NguoiDung [id=" + id + ", email=" + email + ", password=" + password + ", username=" + username
				+ ", status=" + status + ", ngayTao=" + ngayTao + "]";
	}
	
}
