package entities;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBDocument
@DynamoDBTable(tableName = "Users")
public class User implements Serializable {

	private static final long serialVersionUID = 1L;

	@DynamoDBHashKey(attributeName = "userID")
	@DynamoDBAutoGeneratedKey
	private String userID;
	
	@DynamoDBAttribute
	private String tenTaiKhoan;
	
	@DynamoDBAttribute
	private String matKhau;
	
	@DynamoDBAttribute
	private String ngayTao;
	
	@DynamoDBAttribute
	private int trangThai;
	
	public User() {
	}

	public User(String tenTaiKhoan, String matKhau, String ngayTao, int trangThai) {
		super();
		this.tenTaiKhoan = tenTaiKhoan;
		this.matKhau = matKhau;
		this.ngayTao = ngayTao;
		this.trangThai = trangThai;
	}

	public String getUserID() {
		return userID;
	}

	public void setUserID(String userID) {
		this.userID = userID;
	}

	public String getTenTaiKhoan() {
		return tenTaiKhoan;
	}

	public void setTenTaiKhoan(String tenTaiKhoan) {
		this.tenTaiKhoan = tenTaiKhoan;
	}

	public String getMatKhau() {
		return matKhau;
	}

	public void setMatKhau(String matKhau) {
		this.matKhau = matKhau;
	}

	public String getNgayTao() {
		return ngayTao;
	}

	public void setNgayTao(String ngayTao) {
		this.ngayTao = ngayTao;
	}

	public int getTrangThai() {
		return trangThai;
	}

	public void setTrangThai(int trangThai) {
		this.trangThai = trangThai;
	}

	@Override
	public String toString() {
		return "User [userID=" + userID + ", tenTaiKhoan=" + tenTaiKhoan + ", matKhau=" + matKhau + ", ngayTao="
				+ ngayTao + ", trangThai=" + trangThai + "]";
	}
	
	
	

}
